export const ACTIVE_URL='data/match-details/active.json';
export const CONTRACT='tennis-match-details-v1';
export const SPORT='Tennis';
export const COMPONENTS=[['Surface Fit','SurfaceFit'],['Serve vs Return','ServeVsReturn'],['Return vs Serve','ReturnVsServe'],['Hold / Break','HoldBreak'],['Second Serve','SecondServe'],['Base Control','BaseControl']];
const PROFILE='https://dblxlgaming-sudo.github.io/tennis-player-profile/';
const CHARTS='https://dblxlgaming-sudo.github.io/player_stat_charts/';
export const clean=value=>String(value??'').trim();
export const finite=value=>Number.isFinite(value)?value:null;
export const pct=value=>finite(value)===null?'—':`${(value*100).toFixed(1)}%`;
export const score=value=>finite(value)===null?'—':value.toFixed(1);
export async function sha256Hex(bytes,cryptoObject=globalThis.crypto){const digest=await cryptoObject.subtle.digest('SHA-256',bytes);return[...new Uint8Array(digest)].map(value=>value.toString(16).padStart(2,'0')).join('')}
export function operationalBoardDate(locationObject=globalThis.location,dateObject=new Date()){const requested=new URLSearchParams(locationObject?.search||'').get('boardDate');if(requested&&/^\d{4}-\d{2}-\d{2}$/.test(requested))return requested;const year=dateObject.getFullYear(),month=String(dateObject.getMonth()+1).padStart(2,'0'),day=String(dateObject.getDate()).padStart(2,'0');return`${year}-${month}-${day}`}
export function validatePointer(pointer,requestedDate){if(!pointer||pointer.ContractVersion!==CONTRACT)throw new Error('Invalid Match Details contract version');if(pointer.Sport!==SPORT)throw new Error('Invalid Match Details sport');if(pointer.BoardDate!==requestedDate)throw new Error(`NO_CURRENT_DATA:${requestedDate}:${pointer.BoardDate||'unknown'}`);if(!pointer.Release||pointer.Artifact!==`./releases/${pointer.Release}/TripleThreat_Tennis_V2_Match_Details.json`)throw new Error('Invalid Match Details artifact path');if(!/^[a-f0-9]{64}$/.test(pointer.SHA256||''))throw new Error('Invalid Match Details artifact hash');return pointer}
function validateSide(side,player,opponent){if(!side||side.Player!==player||side.Opponent!==opponent)throw new Error('Invalid canonical player identity');if(side.MatchupScoreStatus==='SCORED'&&(!Number.isFinite(side.MatchupScore)||side.MatchupScore<0||side.MatchupScore>100))throw new Error('Invalid Matchup Score');if(side.MatchupScoreStatus==='UNAVAILABLE'&&side.MatchupScore!==null)throw new Error('Invalid unavailable Matchup Score');for(const [,key] of COMPONENTS){if(!side.Components?.[key])throw new Error(`Missing component ${key}`);const value=side.Components[key].Score;if(value!==null&&(!Number.isFinite(value)||value<0||value>100))throw new Error(`Invalid component ${key}`)}}
export function validateArtifact(artifact,pointer){if(!artifact||artifact.ContractVersion!==CONTRACT||artifact.Sport!==SPORT||artifact.BoardDate!==pointer.BoardDate||!Array.isArray(artifact.Matches)||artifact.MatchCount!==artifact.Matches.length)throw new Error('Invalid Match Details release');const ids=new Set();for(const match of artifact.Matches){if(!match.MatchID||ids.has(match.MatchID))throw new Error('Duplicate MatchID');ids.add(match.MatchID);if(!match.PlayerA||!match.PlayerB||match.PlayerA===match.PlayerB)throw new Error('Invalid canonical players');validateSide(match.PlayerAMatchup,match.PlayerA,match.PlayerB);validateSide(match.PlayerBMatchup,match.PlayerB,match.PlayerA)}return artifact}
export function researchUrls(player){return{profile:`${PROFILE}?sport=tennis&player=${encodeURIComponent(player)}`,charts:CHARTS}}
export function scoreTier(side){const band=clean(side?.MatchupScorePresentationBand).toLowerCase();return band==='purple'?'purple':band==='green'?'green':''}
export function componentRows(match){return COMPONENTS.map(([label,key])=>({label,a:match.PlayerAMatchup.Components[key].Score,b:match.PlayerBMatchup.Components[key].Score}))}
export function factualRows(match){const a=match.MatchupAdvantages?.PlayerA||{},b=match.MatchupAdvantages?.PlayerB||{};return[['Total Points Won','TPW','percent'],['Hold','Hold','percent'],['Break','Break','percent'],['Dominance Ratio','DominanceRatio','ratio'],['Second Serve Won','SecondServeWon','percent'],['Break Points Saved','BreakPointsSaved','percent']].map(([label,key,kind])=>({label,kind,a:a[key],b:b[key]}))}
export function counterState(match){const value=match.CounterEvidence;return value?.Status==='UNAVAILABLE'?{available:false,reason:value.Reason||'Unavailable'}:{available:Boolean(value?.Evidence?.length),reason:value?.Reason||'',evidence:value?.Evidence||[]}}
export function conclusionText(match){return match.ModelConclusion?.Status==='AVAILABLE'&&match.ModelConclusion?.SourceField==='Season Projection.ML Note'?clean(match.ModelConclusion.Text):''}
const el=id=>document.getElementById(id);
const escapeHTML=value=>clean(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const unavailable=message=>`<div class="unavailable">${escapeHTML(message)}</div>`;
function scoreHTML(name,side){const value=side.MatchupScoreStatus==='SCORED'?score(side.MatchupScore):'—';const detail=side.MatchupScoreStatus==='SCORED'?[side.MatchupScoreVersion,side.MatchupScoreDataQuality,side.MatchupScorePresentationBand].filter(Boolean).join(' • '):(side.MatchupScoreUnavailableReason||'Unavailable');return`<div class="score" data-tier="${scoreTier(side)}"><span class="score-name">${escapeHTML(name)}</span><strong class="score-value">${value}</strong><span class="score-status">${escapeHTML(detail)}</span></div>`}
function readHTML(label,value,note){return`<div class="read-item"><span class="read-label">${label}</span><strong class="read-value">${escapeHTML(value)}</strong><span class="read-note">${escapeHTML(note)}</span></div>`}
function metric(value,kind,side){const parsed=value===null||value===undefined||value===''?null:Number(value);const shown=parsed===null||!Number.isFinite(parsed)?'—':kind==='percent'?`${(parsed*100).toFixed(1)}%`:kind==='score'?parsed.toFixed(1):`${parsed}`;const width=kind==='score'&&parsed!==null?Math.max(0,Math.min(100,parsed)):kind==='percent'&&parsed!==null?Math.max(0,Math.min(100,parsed*100)):0;return`<div class="metric-value ${side==='b'?'b-side':''}"><span>${shown}</span>${kind!=='ratio'?`<span class="meter"><span class="${side}-fill" style="width:${width}%"></span></span>`:''}</div>`}
function table(rows,a,b,defaultKind){return`<div class="comparison-head"><span>Metric</span><span>${escapeHTML(a)}</span><span>${escapeHTML(b)}</span></div>`+rows.map(row=>`<div class="comparison-row"><span class="metric-name">${row.label}</span>${metric(row.a,row.kind||defaultKind,'a')}${metric(row.b,row.kind||defaultKind,'b')}</div>`).join('')}
function render(match){const a=match.PlayerA,b=match.PlayerB;el('a-name').textContent=a;el('b-name').textContent=b;el('a-form').innerHTML='';el('b-form').innerHTML='';el('meta').textContent=[match.Tournament,match.Surface,match.Round,match.MatchDate,match.MatchTime].filter(Boolean).join(' • ');for(const [side,name] of [['a',a],['b',b]]){const urls=researchUrls(name);el(`${side}-links`).innerHTML=`<a href="${urls.profile}" target="_blank" rel="noopener">Player Profile</a><a href="${urls.charts}" target="_blank" rel="noopener" data-player="${escapeHTML(name)}">Player Stat Charts</a>`}
  el('scores').innerHTML=scoreHTML(a,match.PlayerAMatchup)+scoreHTML(b,match.PlayerBMatchup);const read=match.ModelRead||{};el('model-read').innerHTML=readHTML('Model side',read.ModelPick||'Unavailable','Authoritative model selection')+readHTML('Model win probability',pct(read.ModelWinProbability),'Probability for the listed model side')+readHTML('Market / no-vig probability',pct(read.NoVigMarketProbability),'For the listed model side')+readHTML('Published edge',pct(read.Edge),'Supplied by Tennis V2');
  el('comparison').innerHTML=table(componentRows(match),a,b,'score');el('factual-support').innerHTML=table(factualRows(match),a,b,'percent');const reason=match.MatchupReasoning||{},evidence=[['Surface',reason.Surface],['Serve vs Return',reason.ServeVsReturn],['Return vs Serve',reason.ReturnVsServe],['Control & Pressure',[reason.ControlPressure?.TPWDominanceEdge,reason.ControlPressure?.BreakPointMarketRead].filter(Boolean).join(' • ')],['Second Serve',[reason.SecondServe?.PlayerASecondServeWon,reason.SecondServe?.PlayerBSecondServeWon].filter(Boolean).join(' / ')],['Base Control',reason.BaseControl],['Match Volatility',[reason.ChaosVolatility?.ChaosFlag,reason.ChaosVolatility?.TreeRiskLabel].filter(Boolean).join(' • ')]];el('evidence').innerHTML=evidence.map(([label,value])=>`<div class="evidence-row"><span class="evidence-label">${label}</span><span class="evidence-value">${escapeHTML(value||'Unavailable')}</span></div>`).join('');
  const counter=counterState(match);el('counter-evidence').innerHTML=counter.available?`<div class="evidence-value">${counter.evidence.map(escapeHTML).join('<br>')}</div>`:unavailable(counter.reason);const conclusion=conclusionText(match);el('model-conclusion').innerHTML=conclusion?`<div class="evidence-value">${escapeHTML(conclusion)}</div>`:unavailable('Unavailable');const market=match.SecondaryMarketContext||{};el('market-context').innerHTML=[['Moneyline',read.ModelPick,read.ModelWinProbability],['Spread',market.Spread?.Side,market.Spread?.ModelProbability],['Total',market.Total?.Direction,market.Total?.ModelProbability]].map(([label,value,prob])=>`<div class="market-item"><span class="market-label">${label}</span><strong class="market-value">${escapeHTML(value||'Unavailable')}</strong><span class="market-price">${prob===null||prob===undefined?'Probability unavailable':`Model probability ${pct(prob)}`}</span></div>`).join('');el('view').hidden=false
}
let matches=[];
export async function load({fetchImpl=fetch,requestedDate=operationalBoardDate()}={}){const button=el('refresh');button.disabled=true;el('view').hidden=true;el('status').textContent=`Loading ${requestedDate} matchups…`;try{const pointerResponse=await fetchImpl(`${ACTIVE_URL}?t=${Date.now()}`,{cache:'no-store'});if(!pointerResponse.ok)throw new Error(`Active pointer HTTP ${pointerResponse.status}`);const pointer=validatePointer(await pointerResponse.json(),requestedDate);const artifactUrl=new URL(pointer.Artifact,new URL(ACTIVE_URL,location.href)).href;const releaseResponse=await fetchImpl(`${artifactUrl}?t=${Date.now()}`,{cache:'no-store'});if(!releaseResponse.ok)throw new Error(`Release HTTP ${releaseResponse.status}`);const artifactBytes=await releaseResponse.arrayBuffer();if(await sha256Hex(artifactBytes)!==pointer.SHA256)throw new Error('Release SHA-256 mismatch');const artifact=validateArtifact(JSON.parse(new TextDecoder().decode(artifactBytes)),pointer);matches=artifact.Matches;const select=el('match');select.innerHTML=matches.map((match,index)=>`<option value="${index}">${escapeHTML(`${match.PlayerA} vs ${match.PlayerB}`)}</option>`).join('');select.disabled=!matches.length;if(matches.length){render(matches[0]);el('status').textContent=`${matches.length} matchups • Board ${pointer.BoardDate} • Release ${pointer.Release}`}else el('status').textContent=`No matchups are available for ${requestedDate}.`}catch(error){const stale=String(error.message).startsWith('NO_CURRENT_DATA:');el('status').textContent=stale?`No current Match Details data is available for ${requestedDate}. The active release is for a different BoardDate.`:`Match Details data is unavailable: ${error.message}`;console.error(error)}finally{button.disabled=false}}
if(typeof document!=='undefined'){el('match').addEventListener('change',event=>render(matches[Number(event.target.value)]));el('refresh').addEventListener('click',()=>load());load()}
