import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {ACTIVE_URL,COMPONENTS,componentRows,conclusionText,counterState,operationalBoardDate,researchUrls,scoreTier,sha256Hex,validateArtifact,validatePointer} from '../app.js';
const source=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8'),html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8'),css=fs.readFileSync(new URL('../styles.css',import.meta.url),'utf8');
const side=(player,opponent,value=75)=>({Player:player,Opponent:opponent,MatchupScore:value,MatchupScoreStatus:'SCORED',MatchupScorePresentationBand:'PURPLE',Components:Object.fromEntries(COMPONENTS.map(([,key],index)=>[key,{Score:50+index}]))});
const match={MatchID:'A_B_1001',BoardDate:'2026-10-01',PlayerA:'A',PlayerB:'B',PlayerAMatchup:side('A','B'),PlayerBMatchup:side('B','A',64),CounterEvidence:{Status:'UNAVAILABLE',Reason:'NO_AUTHORITATIVE_MATCHUP_COUNTER_EVIDENCE_FIELD',Evidence:[]},ModelConclusion:{Status:'AVAILABLE',SourceField:'Season Projection.ML Note',Text:'Authoritative note'}};
const pointer={ContractVersion:'tennis-match-details-v1',Sport:'Tennis',BoardDate:'2026-10-01',Release:'r1',Artifact:'./releases/r1/TripleThreat_Tennis_V2_Match_Details.json',SHA256:'a'.repeat(64),GeneratedAt:'2026-10-01T00:00:00Z'};
const artifact={ContractVersion:'tennis-match-details-v1',Sport:'Tennis',BoardDate:'2026-10-01',MatchCount:1,Matches:[match]};
test('active pointer loading uses repository JSON',()=>assert.equal(ACTIVE_URL,'data/match-details/active.json'));
test('immutable release path is required',()=>assert.equal(validatePointer(pointer,'2026-10-01').Artifact,pointer.Artifact));
test('frontend can verify immutable release SHA-256',async()=>assert.equal(await sha256Hex(new TextEncoder().encode('abc')),'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad'));
test('BoardDate equality passes',()=>assert.equal(validatePointer(pointer,'2026-10-01').BoardDate,'2026-10-01'));
test('stale BoardDate is rejected',()=>assert.throws(()=>validatePointer(pointer,'2026-10-03'),/NO_CURRENT_DATA/));
test('there is no yesterday fallback',()=>assert.doesNotMatch(source,/yesterday|setDate\s*\(/i));
test('there is no Google Sheet request',()=>assert.doesNotMatch(source,/docs\.google|spreadsheet|output=csv|Glide/i));
test('canonical player orientation validates',()=>assert.equal(validateArtifact(artifact,pointer).Matches[0].PlayerA,'A'));
test('both Matchup Scores remain distinct',()=>assert.deepEqual([match.PlayerAMatchup.MatchupScore,match.PlayerBMatchup.MatchupScore],[75,64]));
test('all six authoritative components map',()=>assert.deepEqual(componentRows(match).map(row=>row.label),COMPONENTS.map(row=>row[0])));
test('Model Read remains separate from Matchup Score',()=>{assert.match(html,/Model Read/);assert.match(html,/Matchup Score/)});
test('authoritative reasoning fields are mapped',()=>assert.match(source,/MatchupReasoning/));
test('Counter Evidence unavailable reason is preserved',()=>assert.deepEqual(counterState(match),{available:false,reason:'NO_AUTHORITATIVE_MATCHUP_COUNTER_EVIDENCE_FIELD'}));
test('Model Conclusion uses Season Projection ML Note',()=>assert.equal(conclusionText(match),'Authoritative note'));
test('null unavailable score is accepted',()=>{const copy=structuredClone(artifact);copy.Matches[0].PlayerAMatchup.MatchupScore=null;copy.Matches[0].PlayerAMatchup.MatchupScoreStatus='UNAVAILABLE';assert.doesNotThrow(()=>validateArtifact(copy,pointer))});
test('research links remain present',()=>{assert.match(researchUrls('A').profile,/tennis-player-profile/);assert.match(researchUrls('A').charts,/player_stat_charts/)});
test('purple presentation uses supplied band without thresholds',()=>{assert.equal(scoreTier(match.PlayerAMatchup),'purple');assert.match(css,/data-tier="purple/)});
test('desktop and mobile styles avoid horizontal overflow',()=>{assert.match(css,/@media\(max-width:720px\)/);assert.doesNotMatch(css,/overflow-x:\s*auto/)});
test('operational date can be explicitly requested for fixture smoke',()=>assert.equal(operationalBoardDate({search:'?boardDate=2026-10-01'},new Date()),'2026-10-01'));
