import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {ACTIVE_PATH,COMPONENTS,acquireLock,assertAllowedChanges,assertNotOlder,gitSafety,intendedPaths,isIdempotent,needsPush,pollLive,pushArgs,sha256,validateArtifact,validateCandidate,validatePointer} from '../scripts/match-details-publisher-lib.mjs';
const side=(p,o,s=60)=>({Player:p,Opponent:o,MatchupScore:s,MatchupScoreStatus:'SCORED',Components:Object.fromEntries(COMPONENTS.map(k=>[k,{Score:50,Available:'Yes'}]))});
const match={MatchID:'A_B_1001',BoardDate:'2026-10-01',PlayerA:'A',PlayerB:'B',PlayerAMatchup:side('A','B'),PlayerBMatchup:side('B','A'),ModelRead:{ModelWinProbability:.6},CounterEvidence:{Status:'UNAVAILABLE',Reason:'NO_AUTHORITATIVE_MATCHUP_COUNTER_EVIDENCE_FIELD',Evidence:[]}};
const artifact={ContractVersion:'tennis-match-details-v1',Sport:'Tennis',BoardDate:'2026-10-01',GeneratedAt:'2026-10-01T00:00:00Z',MatchCount:1,Matches:[match]};
const bytes=Buffer.from(JSON.stringify(artifact));const pointer={ContractVersion:'tennis-match-details-v1',Sport:'Tennis',BoardDate:'2026-10-01',Release:'2026-10-01-test',Artifact:'./releases/2026-10-01-test/TripleThreat_Tennis_V2_Match_Details.json',SHA256:sha256(bytes),GeneratedAt:'2026-10-01T00:00:00Z'};const pointerBytes=Buffer.from(JSON.stringify(pointer));
test('valid publication candidate',()=>assert.equal(validateCandidate(pointerBytes,bytes).artifact.MatchCount,1));
test('invalid pointer',()=>assert.throws(()=>validateCandidate(Buffer.from('{'),bytes),/pointer JSON/));
test('invalid artifact',()=>assert.throws(()=>validateCandidate(pointerBytes,Buffer.from('{')),/artifact JSON/));
test('SHA mismatch',()=>assert.throws(()=>validateCandidate(Buffer.from(JSON.stringify({...pointer,SHA256:'f'.repeat(64)})),bytes),/SHA-256 mismatch/));
test('ContractVersion mismatch',()=>assert.throws(()=>validatePointer({...pointer,ContractVersion:'v0'}),/ContractVersion/));
test('Sport mismatch',()=>assert.throws(()=>validatePointer({...pointer,Sport:'WNBA'}),/Sport/));
test('duplicate MatchID',()=>assert.throws(()=>validateArtifact({...artifact,MatchCount:2,Matches:[match,structuredClone(match)]},pointer),/Duplicate/));
test('duplicate player-side identity',()=>{const copy=structuredClone(artifact);copy.Matches[0].PlayerB='A';assert.throws(()=>validateArtifact(copy,pointer),/Duplicate player-side/)});
test('invalid probability',()=>{const copy=structuredClone(artifact);copy.Matches[0].ModelRead.ModelWinProbability=1.2;assert.throws(()=>validateArtifact(copy,pointer),/ModelWinProbability/)});
test('inconsistent Matchup Score state/value',()=>{const copy=structuredClone(artifact);copy.Matches[0].PlayerAMatchup.MatchupScoreStatus='UNAVAILABLE';assert.throws(()=>validateArtifact(copy,pointer),/state\/value/)});
test('unavailable values are preserved',()=>{const copy=structuredClone(artifact);copy.Matches[0].PlayerAMatchup.MatchupScoreStatus='UNAVAILABLE';copy.Matches[0].PlayerAMatchup.MatchupScore=null;assert.equal(validateArtifact(copy,pointer).Matches[0].PlayerAMatchup.MatchupScore,null)});
test('stale BoardDate mismatch',()=>assert.throws(()=>validateArtifact({...artifact,BoardDate:'2026-09-30'},pointer),/BoardDate/));
test('older candidate cannot replace newer active',()=>assert.throws(()=>assertNotOlder(pointer,{...pointer,BoardDate:'2026-10-02'}),/Older/));
test('staging failure leaves source pointer unchanged',()=>{const before=JSON.stringify(pointer);assert.throws(()=>validateCandidate(pointerBytes,Buffer.from('bad')),/artifact JSON/);assert.equal(JSON.stringify(pointer),before)});
test('unrelated dirty-tree rejection',()=>assert.throws(()=>gitSafety({branch:'main',origin:'https://github.com/dblxlgaming-sudo/triple-threat-match-detail.git',dirty:['app.js'],staged:[]},'https://github.com/dblxlgaming-sudo/triple-threat-match-detail.git'),/dirty/));
test('unrelated staged-file rejection',()=>assert.throws(()=>gitSafety({branch:'main',origin:'https://github.com/dblxlgaming-sudo/triple-threat-match-detail.git',dirty:[],staged:['app.js']},'https://github.com/dblxlgaming-sudo/triple-threat-match-detail.git'),/staged/));
test('wrong branch rejected',()=>assert.throws(()=>gitSafety({branch:'dev',origin:'x',dirty:[],staged:[]},'x'),/branch main/));
test('wrong remote rejected',()=>assert.throws(()=>gitSafety({branch:'main',origin:'x',dirty:[],staged:[]},'y'),/remote/));
test('lock contention uses bounded timeout',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'md-lock-'));fs.mkdirSync(path.join(root,'.git'));const release=await acquireLock(root,{waitMs:20,pollMs:5});await assert.rejects(()=>acquireLock(root,{waitMs:10,pollMs:5}),/lock timeout/);release();fs.rmSync(root,{recursive:true,force:true})});
test('idempotent same release and SHA',()=>assert.equal(isIdempotent(pointer,structuredClone(pointer)),true));
test('idempotent current HEAD does not push unnecessarily',()=>assert.equal(needsPush(0),false));
test('failed-push recovery retries when local HEAD is ahead',()=>assert.equal(needsPush(1),true));
test('safe push-failure recovery retains exact intended paths',()=>assert.deepEqual(intendedPaths(pointer),[ACTIVE_PATH,'data/match-details/releases/2026-10-01-test/TripleThreat_Tennis_V2_Match_Details.json']));
test('Pages timeout reports failure',async()=>await assert.rejects(()=>pollLive({baseUrl:'https://invalid.test',pointer,timeoutMs:5,pollMs:1,fetchImpl:async()=>({ok:false,status:404})}),/timeout/));
test('live pointer mismatch reports failure',async()=>await assert.rejects(()=>pollLive({baseUrl:'https://x',pointer,timeoutMs:5,pollMs:1,fetchImpl:async()=>({ok:true,arrayBuffer:async()=>Buffer.from(JSON.stringify({...pointer,Release:'other'}))})}),/timeout/));
test('live artifact hash mismatch reports failure',async()=>{let count=0;await assert.rejects(()=>pollLive({baseUrl:'https://x',pointer,timeoutMs:5,pollMs:1,fetchImpl:async()=>++count%2?{ok:true,arrayBuffer:async()=>pointerBytes}:{ok:true,arrayBuffer:async()=>Buffer.from('wrong')}}),/timeout/)});
test('last-known-good remains unchanged after rejection',()=>{const current=structuredClone(pointer);assert.throws(()=>assertNotOlder({...pointer,BoardDate:'2026-09-01'},current));assert.deepEqual(current,pointer)});
test('no force-push path exists',()=>assert.deepEqual(pushArgs(),['push','origin','main']));
test('allowlist rejects application files',()=>assert.throws(()=>assertAllowedChanges(['app.js'],pointer),/Unrelated/));
